name: Bump and release
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.0
                    
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3.8.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'
        skip-version-file: 'true'
        skip-on-empty: 'true'
        skip-commit: 'false'
    
    - name: Write version.txt file
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      shell: bash
      run: echo ${{ steps.changelog.outputs.tag }} > version.txt
      
    - name: Update version.txt file
      uses: test-room-7/action-update-file@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      with:
        file-path: version.txt
        commit-msg: Bump version.txt and CHANGELOG.md
        github-token: ${{ secrets.GITHUB_TOKEN }}
                     
    - name: Create version release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:     
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ steps.changelog.outputs.tag }}
        prerelease: false
        title: ${{ steps.changelog.outputs.tag }}
        files: |
          LICENSE
          *.cmd
          *.sh
